In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pickle
import random

from numpy import random


a1 = random.randint(65536, size=(2**16))
a2 = random.randint(131072, size=(2**17))

with open('/content/drive/MyDrive/a1.pkl', 'wb') as f:
  pickle.dump(a1, f)

with open('/content/drive/MyDrive/a2.pkl', 'wb') as f:
  pickle.dump(a2, f)

# Naive (Without preprocessing)

In [ ]:
import numpy as np
import time

def range_minimum_query(arr, left, right):
    if left < 0 or right >= len(arr) or left > right:
        raise ValueError("Invalid range specified")

    minimum = arr[left]
    for i in range(left + 1, right + 1):
        if arr[i] < minimum:
            minimum = arr[i]
    return minimum


s_time = time.time()

print("Minimum value between i and j:", range_minimum_query(arr, 0, 34000))

e_time = time.time()

print(e_time-s_time)

# **Naive** (Full Processing)

In [ ]:
import time

with open('/content/drive/MyDrive/a2.pkl', 'rb') as f:
  lst = pickle.load(f)

count = 0
n = len(lst)
matrix = [[0]*n]*n

start_time = time.time()

for start in range(n):
  for end in range(start + 1, n + 1):
    sub_array = lst[start:end]
    min = 0
    for i in range(len(sub_array)):
      if sub_array[i] < min:
        min = sub_array[i]

      matrix[start][end] = min
    # count +=1

end_time = time.time()
print("--- %s seconds ---" % (end_time - start_time))
# print(count)

# Dynamic Programming

In [ ]:
import numpy as np

with open('/content/drive/MyDrive/a2.pkl', 'rb') as f:
  lst = pickle.load(f)

n = len(lst)

matrix = [[0]*n]*n

for i in range(n):
  matrix[i][i] = lst[i]

matrix_np = np.array()

diags = [matrix_np[::-1,:].diagonal(i) for i in range(-3,4)]
diags.extend(matrix.diagonal(i) for i in range(3,-4,-1))
print [n.tolist() for n in diags]

In [ ]:
import numpy as np

matrix = np.array(
         [[-2,  5,  3,  2],
          [ 9, -6,  5,  1],
          [ 3,  2,  7,  3],
          [-1,  8, -4,  8]])

diags = [matrix[::-1,:].diagonal(i) for i in range(-3,4)]
print(diags)
print('------------')
for i in range(3,-4,-1):
  print(matrix.diagonal(i))
print('------------')
diags.extend(matrix.diagonal(i) for i in range(3,-4,-1))
print([n.tolist() for n in diags])

[array([-2]), array([9, 5]), array([ 3, -6,  3]), array([-1,  2,  5,  2]), array([8, 7, 1]), array([-4,  3]), array([8])]
------------
[2]
[3 1]
[5 5 3]
[-2 -6  7  8]
[ 9  2 -4]
[3 8]
[-1]
------------
[[-2], [9, 5], [3, -6, 3], [-1, 2, 5, 2], [8, 7, 1], [-4, 3], [8], [2], [3, 1], [5, 5, 3], [-2, -6, 7, 8], [9, 2, -4], [3, 8], [-1]]


In [ ]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.diag(x, k=1)

array([1, 5])

In [ ]:
import numpy as np

def get_diagonal_indices(arr):
    n_rows, n_cols = arr.shape
    diagonal_indices = {}

    # Loop through all possible offsets
    for offset in range(-n_rows + 1, n_cols):
        indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
        diagonal_indices[offset] = [(i, j + offset) for i, j in zip(*indices)]

    return diagonal_indices

# example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

diagonal_indices = get_diagonal_indices(arr)

# Print indices for each diagonal
for offset, indices in diagonal_indices.items():
    print(f'Offset {offset}: {indices}')

Offset -2: [(0, -2), (1, -1), (2, 0)]
Offset -1: [(0, -1), (1, 0), (2, 1)]
Offset 0: [(0, 0), (1, 1), (2, 2)]
Offset 1: [(0, 1), (1, 2)]
Offset 2: [(0, 2)]


In [ ]:
import numpy as np
import pickle
import random
import gc

# with open('/content/drive/MyDrive/a2.pkl', 'rb') as f:
#   lst = pickle.load(f)

lst = random.sample(range(1,65537), 2**16)

n = len(lst)

matrix = [[0]*n]*n

for i in range(n):
  matrix[i][i] = lst[i]

arr = np.array(matrix)

# arr = np.array([[1, 2, 3],
#                 [4, 5, 6],
#                 [7, 8, 9]])

n_rows, n_cols = arr.shape
# diagonal_indices = {}
# diags = {}

# Loop through all possible offsets
for offset in range(1, n_cols):
  gc.collect()
  indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
  # print(indices)
  # diagonal_indices[offset] = [(i, j + offset) for i, j in zip(*indices)]
  diagonal_indices = [(i, j + offset) for i, j in zip(*indices)]
  # print(diagonal_indices)
  # diags[offset] = np.diag(arr, k=offset)
  # print(diags)
  # print('-------------------------')
  del indices

  for each in diagonal_indices:
    gc.collect()
    row_number = each[0]
    col_number = each[1]
    x = arr[row_number, col_number-1]
    y = arr[row_number+1, col_number]
    arr[each[0], each[1]] = min(x, y)
  del indices, diagonal_indices

# for each in diagonal_indices:
#   print(type(each))
# print(diagonal_indices)
# print(diags)

print(arr)

In [ ]:
indices

(array([0]), array([0]))

In [ ]:
q = (1, 3)
q[1]

3

In [ ]:
import numpy as np
import random
import gc

lst = random.sample(range(1,65537), 2**16)

n = len(lst)

matrix = [[0]*n]*n

for i in range(n):
  matrix[i][i] = lst[i]

arr = np.array(matrix)

n_rows, n_cols = arr.shape

# Loop through all possible offsets
for offset in range(1, n_cols):
  gc.collect()
  indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
  diagonal_indices = [(i, j + offset) for i, j in zip(*indices)]
  del indices

  for each in diagonal_indices:
    gc.collect()
    row_number = each[0]
    col_number = each[1]
    x = arr[row_number, col_number-1]
    y = arr[row_number+1, col_number]
    arr[each[0], each[1]] = min(x, y)
  del indices, diagonal_indices



print(arr)

In [ ]:
import numpy as np
import random
import gc
import time

# lst = random.sample(range(1, 1000), 2**16)  # Be aware this creates a list of 65536 numbers

# lst = np.random.randint(low = 1,high=100,size=35000)
lst = np.random.randint(low = 1,high=100,size=2**14)
n = len(lst)

matrix = [[0 for _ in range(n)] for _ in range(n)]

start_time = time.time()

for i in range(n):
    matrix[i][i] = lst[i]

arr = np.array(matrix, dtype=np.int8)

n_rows, n_cols = arr.shape

for offset in range(1, n_cols):
    # gc.collect()
    indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
    diagonal_indices = [(i, j + offset) for i, j in zip(*indices)]
    # del indices

    for each in diagonal_indices:
        # gc.collect()
        row_number = each[0]
        col_number = each[1]
        x = arr[row_number, col_number-1]
        y = arr[row_number+1, col_number]
        arr[each[0], each[1]] = min(x, y)
    # del indices, diagonal_indices

end_time = time.time()
print("--- %s seconds ---" % (end_time - start_time))

print(arr)

--- 294.05405616760254 seconds ---
[[26 26 26 ...  1  1  1]
 [ 0 91 27 ...  1  1  1]
 [ 0  0 27 ...  1  1  1]
 ...
 [ 0  0  0 ... 55 17 17]
 [ 0  0  0 ...  0 17 17]
 [ 0  0  0 ...  0  0 72]]


In [ ]:
s_time = time.time()
arr[0][34000]
e_time = time.time()
print("Minimum value between indices 0 and 34000:", arr[0][34000])
print(e_time - s_time)

Minimum value between indices 0 and 34000: 1
0.00013685226440429688


In [ ]:
2**16

65536

In [ ]:
2**15

32768

# Block Decomposition

In [ ]:
def find_min(lst, minima_list , i, j):
  start_block = int(i/b)
  end_block = int(j/b)

  i_complete_fit = False
  j_complete_fit = False

  if i == b * start_block:
    first_whole_block = start_block
    i_complete_fit = True
  else:
    first_whole_block = start_block + 1

  if j == (b * (end_block+1)) -1:
    last_whole_block = end_block
    j_complete_fit = True
  else:
    last_whole_block = end_block - 1

  min_value = min(minima_list[first_whole_block:last_whole_block+1])

  if not i_complete_fit:
    before_min = min(lst[i:b * (start_block+1)])
    min_value = min(min_value, before_min)

  if not j_complete_fit:
    after_min = min(lst[b*end_block:j+1])
    min_value = min(min_value, after_min)

  return min_value


In [ ]:
import numpy as np
import random
import gc
import time

lst = np.random.randint(low = 1,high=1000,size=2**17)
n = len(lst)

b = 256
minima_list = []

s_time = time.time()
for i in range(0, n, b):
  minima = min(lst[i:i+b])
  minima_list.append(minima)

e_time = time.time()

print("preprocess time:", (e_time - s_time))

start_time = time.time()
min_val = find_min(lst , minima_list, i = 0, j = 34000)
end_time = time.time()

print("query time: ", (end_time - start_time))

print("minimum_value:", min_val)

preprocess time: 0.023359060287475586
query time:  0.00020051002502441406
minimum_value: 1


In [ ]:
e = 5
b = 3
print(int(e/b))

1


In [ ]:
import math
import numpy as np
import time

# Initialize array and size
# arr = [1, 3, 2, 7, 9, 11]
arr = np.random.randint(low = 1,high=1000,size=2**16)
n = len(arr)

s_time = time.time()
# Compute the log values
log = [0] * (n + 1)
for i in range(2, n + 1):
    log[i] = log[i // 2] + 1

# Initialize Sparse Table
K = log[n] + 1  # Maximum j
st = [[0] * K for _ in range(n)]

# Fill the first column of Sparse Table
for i in range(n):
    st[i][0] = arr[i]

# Fill the Sparse Table
for j in range(1, K):
    i = 0
    while i + (1 << j) - 1 < n:
        st[i][j] = min(st[i][j - 1], st[i + (1 << (j - 1))][j - 1])
        i += 1

e_time = time.time()

print('Preprocess Time: ', (e_time - s_time))

Preprocess Time:  0.7853639125823975


In [ ]:
def range_min_query(L, R):
    j = log[R - L + 1]
    return min(st[L][j], st[R - (1 << j) + 1][j])

# Example query
L, R = 0, 34000  # Find the minimum in the range from index 1 to index 4

start_time = time.time()
result = range_min_query(L, R)
end_time = time.time()

print('Preprocess Time: ', (e_time - s_time))
print("Query Time: ", (end_time - start_time))
print("Minimum value: ", result)  # Output: 2

Preprocess Time:  0.7853639125823975
Query Time:  0.00011968612670898438
Minimum value:  1


# Hybrid Method

In [ ]:
def sparse_table(arr, L, R):
  n = len(arr)
  # Compute the log values
  log = [0] * (n + 1)
  for i in range(2, n + 1):
      log[i] = log[i // 2] + 1

  # Initialize Sparse Table
  K = log[n] + 1  # Maximum j
  st = [[0] * K for _ in range(n)]

  # Fill the first column of Sparse Table
  for i in range(n):
      st[i][0] = arr[i]

  # Fill the Sparse Table
  for j in range(1, K):
      i = 0
      while i + (1 << j) - 1 < n:
          st[i][j] = min(st[i][j - 1], st[i + (1 << (j - 1))][j - 1])
          i += 1

  j = log[R - L + 1]
  return min(st[L][j], st[R - (1 << j) + 1][j])

In [ ]:
def find_min(lst, minima_list , i, j):
  start_block = int(i/b)
  end_block = int(j/b)

  i_complete_fit = False
  j_complete_fit = False

  if i == b * start_block:
    first_whole_block = start_block
    i_complete_fit = True
  else:
    first_whole_block = start_block + 1

  if j == (b * (end_block+1)) -1:
    last_whole_block = end_block
    j_complete_fit = True
  else:
    last_whole_block = end_block - 1

  min_value = min(minima_list[first_whole_block:last_whole_block+1])

  if not i_complete_fit:
    before_min = min(lst[i:b * (start_block+1)])
    min_value = min(min_value, before_min)

  if not j_complete_fit:
    after_min = min(lst[b*end_block:j+1])
    min_value = min(min_value, after_min)

  return min_value


In [ ]:
import numpy as np
import random
import gc
import time

lst = np.random.randint(low = 1,high=1000,size=2**16)
n = len(lst)

b = 256
minima_list = []

s_time = time.time()
for i in range(0, n, b):
  # minima = min(lst[i:i+b])
  minima = sparse_table(lst[i:i+b], 0, b-1)
  minima_list.append(minima)

e_time = time.time()

print("preprocess time:", (e_time - s_time))

start_time = time.time()
min_val = find_min(lst , minima_list, i = 0, j = 34000)
end_time = time.time()

print("query time: ", (end_time - start_time))

print("minimum_value:", min_val)

preprocess time: 0.3100755214691162
query time:  0.00017976760864257812
minimum_value: 1


In [ ]:
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def build_cartesian_tree(arr):
    if not arr:
        return None
    # Finding the index of the minimum element
    min_index = min(range(len(arr)), key=arr.__getitem__)
    node = Node(arr[min_index])
    node.left = build_cartesian_tree(arr[:min_index])
    node.right = build_cartesian_tree(arr[min_index + 1:])
    return node

def rmq_preprocessing(root):
    # Perform a DFS and store the indices of values for future queries
    # Flatten the Cartesian Tree in a list while recording indices in order
    order = []
    indices = []

    def dfs(node):
        if not node:
            return
        order.append(node.value)
        indices.append(arr.index(node.value))  # Store the original index
        dfs(node.left)
        dfs(node.right)

    dfs(root)
    return order, indices

def query_rmq(l, r, arr, order, indices):
    # Find the minimum in the range [l, r]
    min_value = float('inf')
    min_index = -1
    for i in range(l, r + 1):
        if arr[i] < min_value:
            min_value = arr[i]
            min_index = i
    return min_value, min_index

# Example of using the Cartesian Tree for RMQ
if __name__ == "__main__":
    arr = [3, 2, 1, 4, 5]

    # Step 1: Build the Cartesian Tree
    cartesian_tree_root = build_cartesian_tree(arr)

    # Step 2: Preprocess the tree for RMQ
    order, indices = rmq_preprocessing(cartesian_tree_root)

    # Step 3: Perform RMQ
    l = 1  # Left index of the query
    r = 3  # Right index of the query
    min_value, min_index = query_rmq(l, r, arr, order, indices)

    print(f"Minimum value in range [{l}, {r}] is: {min_value} at index {min_index}")


Minimum value in range [1, 3] is: 1 at index 2


In [ ]:
print(order)
print(indices)

[1, 2, 3, 4, 5]
[2, 1, 0, 3, 4]


# Fischer-Heun

In [ ]:
def sparse_table(arr, L, R):
  n = len(arr)
  # Compute the log values
  log = [0] * (n + 1)
  for i in range(2, n + 1):
      log[i] = log[i // 2] + 1

  # Initialize Sparse Table
  K = log[n] + 1  # Maximum j
  st = [[0] * K for _ in range(n)]

  # Fill the first column of Sparse Table
  for i in range(n):
      st[i][0] = arr[i]

  # Fill the Sparse Table
  for j in range(1, K):
      i = 0
      while i + (1 << j) - 1 < n:
          st[i][j] = min(st[i][j - 1], st[i + (1 << (j - 1))][j - 1])
          i += 1

  j = log[R - L + 1]
  return min(st[L][j], st[R - (1 << j) + 1][j])

In [ ]:
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def build_cartesian_tree(arr):
    if not arr:
        return None
    # Finding the index of the minimum element
    min_index = min(range(len(arr)), key=arr.__getitem__)
    node = Node(arr[min_index])
    node.left = build_cartesian_tree(arr[:min_index])
    node.right = build_cartesian_tree(arr[min_index + 1:])
    return node

def rmq_preprocessing(root):
    # Perform a DFS and store the indices of values for future queries
    # Flatten the Cartesian Tree in a list while recording indices in order
    order = []
    indices = []

    def dfs(node):
        if not node:
            return
        order.append(node.value)
        indices.append(arr.index(node.value))  # Store the original index
        dfs(node.left)
        dfs(node.right)

    dfs(root)
    return order, indices

# def query_rmq(l, r, arr, order, indices):
#     # Find the minimum in the range [l, r]
#     min_value = float('inf')
#     min_index = -1
#     for i in range(l, r + 1):
#         if arr[i] < min_value:
#             min_value = arr[i]
#             min_index = i
#     # return min_value, min_index
#     return min_index

# Example of using the Cartesian Tree for RMQ
# if __name__ == "__main__":
#     # arr = [3, 2, 1, 4, 5]

#     tree_dict = {}
#     total_dict = {}

#     block_num = 0
#     for i in range(0, n, b):
#       block = lst[i:i+b]
#       found = False
#       cartesian_tree_root = build_cartesian_tree(block)
#       indices = rmq_preprocessing(cartesian_tree_root)
#       for key, value in tree_dict.items():
#         if indices == value:
#           total_dict[block_num] = total_dict[key]
#           found = True
#           break
#       if not found:
#         tree_dict[block_num] = indices
#         matrix = [[0 for _ in range(n)] for _ in range(n)]
#         for i in range(n):
#             matrix[i][i] = lst[i]

#         arr = np.array(matrix, dtype=np.int8)

#         n_rows, n_cols = arr.shape

#         for offset in range(1, n_cols):
#             # gc.collect()
#             indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
#             diagonal_indices = [(i, j + offset) for i, j in zip(*indices)]
#             # del indices

#             for each in diagonal_indices:
#                 # gc.collect()
#                 row_number = each[0]
#                 col_number = each[1]
#                 x = arr[row_number, col_number-1]
#                 y = arr[row_number+1, col_number]
#                 arr[each[0], each[1]] = min(x, y)


#         total_dict[block_num] = matrix



    # # Step 1: Build the Cartesian Tree
    # cartesian_tree_root = build_cartesian_tree(arr)

    # # Step 2: Preprocess the tree for RMQ
    # order, indices = rmq_preprocessing(cartesian_tree_root)

    # # Step 3: Perform RMQ
    # l = 1  # Left index of the query
    # r = 3  # Right index of the query
    # # min_value, min_index = query_rmq(l, r, arr, order, indices)
    # min_index = query_rmq(l, r, arr, order, indices)

    # # print(f"Minimum value in range [{l}, {r}] is: {min_value} at index {min_index}")



In [ ]:
def find_min(lst, minima_list , i, j):
  start_block = int(i/b)
  end_block = int(j/b)

  i_complete_fit = False
  j_complete_fit = False

  if i == b * start_block:
    first_whole_block = start_block
    i_complete_fit = True
  else:
    first_whole_block = start_block + 1

  if j == (b * (end_block+1)) -1:
    last_whole_block = end_block
    j_complete_fit = True
  else:
    last_whole_block = end_block - 1

  # min_value = min(minima_list[first_whole_block:last_whole_block+1])
  min_value = sparse_table(lst[i:i+b], 0, b-1)

  if not i_complete_fit:
    # first = i - (start_block * 4)
    # last = 3
    # before_min = total_dict[start_block][first, last]
    before_min = min(lst[i:b * (start_block+1)])
    min_value = min(min_value, before_min)

  if not j_complete_fit:
    # first = 0
    # last = j - (end_block * 4)
    # after_min = total_dict[end_block][first, last]
    after_min = min(lst[b*end_block:j+1])
    min_value = min(min_value, after_min)

  return min_value


In [ ]:
import numpy as np
import random
import gc
import time

lst = np.random.randint(low = 1,high=1000,size=2**16)
n = len(lst)

b = 4
minima_list = []

s_time = time.time()
for i in range(0, n, b):
  minima = min(lst[i:i+b])
  minima_list.append(minima)

tree_dict = {}
total_dict = {}

block_num = 0
# for i in range(0, n, b):
#   block = lst[i:i+b].tolist()
#   found = False
#   print(block)
#   print('iiiiiiiiiiiiiiiiiii')
#   cartesian_tree_root = build_cartesian_tree(block)
#   indices = rmq_preprocessing(cartesian_tree_root)
#   for key, value in tree_dict.items():
#     if indices == value:
#       total_dict[block_num] = total_dict[key]
#       found = True
#       break
#   if not found:
#     tree_dict[block_num] = indices
#     matrix = [[0 for _ in range(n)] for _ in range(n)]
#     for i in range(n):
#         matrix[i][i] = lst[i]

#     arr = np.array(matrix, dtype=np.int8)

#     n_rows, n_cols = arr.shape

#     for offset in range(1, n_cols):
#         # gc.collect()
#         indices = np.diag_indices(min(n_rows, n_cols - offset))  # Get diagonal indices
#         diagonal_indices = [(i, j + offset) for i, j in zip(*indices)]
#         # del indices

#         for each in diagonal_indices:
#             # gc.collect()
#             row_number = each[0]
#             col_number = each[1]
#             x = arr[row_number, col_number-1]
#             y = arr[row_number+1, col_number]
#             arr[each[0], each[1]] = min(x, y)


#     total_dict[block_num] = matrix


e_time = time.time()

print("preprocess time:", (e_time - s_time))

start_time = time.time()
min_val = find_min(lst , minima_list, i = 0, j = 34000)
end_time = time.time()

print("query time: ", (end_time - start_time))


preprocess time: 0.030535459518432617
query time:  0.00010824203491210938
